// <auto-generated />
using CarseerAssignment;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarseerAssignment.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20230128095054_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarseerAssignment.Models.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("bodystyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("enginelocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horsepower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numofcylinders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numofdoors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
